begin;

alter table public.orders
  add column if not exists payment_method text,
  add column if not exists delivery_method text,
  add column if not exists admin_notes text,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  icon text not null default '⚙',
  price numeric(12,2) not null default 0 check (price >= 0),
  duration_label text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_orders (
  id bigint generated by default as identity primary key,
  service_id bigint references public.services(id) on delete set null,
  customer_name text not null,
  customer_phone text,
  customer_email text,
  device text not null,
  issue text not null default '',
  technical_notes text,
  estimate numeric(12,2) not null default 0 check (estimate >= 0),
  final_price numeric(12,2) check (final_price is null or final_price >= 0),
  status text not null default 'recebido' check (status in ('recebido','diagnostico','aguardando_aprovacao','em_reparo','pronto','entregue','cancelado')),
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  eyebrow text not null default '',
  title text not null,
  subtitle text not null default '',
  image_url text,
  link_label text not null default 'Ver oferta',
  link_url text not null default '#offers',
  active boolean not null default true,
  sort_order integer not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint banners_schedule_valid check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  store_name text not null default 'BLACKOUT Infor Games',
  support_phone text not null default '',
  whatsapp text not null default '',
  support_email text not null default '',
  address text not null default '',
  business_hours text not null default '',
  instagram text not null default '',
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  free_shipping_min numeric(12,2) not null default 0 check (free_shipping_min >= 0),
  maintenance_mode boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.services (name, description, icon, price, duration_label, sort_order)
values
  ('Limpeza Preventiva', 'Limpeza completa, troca de pasta térmica e revisão de refrigeração.', '🧹', 120, '1 a 2 dias', 1),
  ('Manutenção de Consoles', 'Diagnóstico e reparo de PlayStation, Xbox e Nintendo.', '🎮', 150, '2 a 5 dias', 2),
  ('Upgrade de PC', 'Instalação de componentes, otimização e testes de estabilidade.', '🖥️', 100, '1 a 3 dias', 3),
  ('Reparo de Controles', 'Correção de drift, botões, conectores e falhas eletrônicas.', '🕹️', 80, '1 a 3 dias', 4)
on conflict (name) do nothing;

insert into public.store_settings
  (id, store_name, support_phone, whatsapp, address, business_hours)
values
  (1, 'BLACKOUT Infor Games', '(75) 9 8312-1210', '5575983121210', 'Rua Nossa Senhora da Saúde, 432, Centro, Ribeira do Pombal - BA', 'Segunda a sábado, das 8h às 18h')
on conflict (id) do update
set address = replace(store_settings.address, 'Ribeirão do Pombal', 'Ribeira do Pombal')
where store_settings.address like '%Ribeirão do Pombal%';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();
drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services for each row execute function public.set_updated_at();
drop trigger if exists service_orders_set_updated_at on public.service_orders;
create trigger service_orders_set_updated_at before update on public.service_orders for each row execute function public.set_updated_at();
drop trigger if exists banners_set_updated_at on public.banners;
create trigger banners_set_updated_at before update on public.banners for each row execute function public.set_updated_at();
drop trigger if exists store_settings_set_updated_at on public.store_settings;
create trigger store_settings_set_updated_at before update on public.store_settings for each row execute function public.set_updated_at();

alter table public.services enable row level security;
alter table public.service_orders enable row level security;
alter table public.banners enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists "Public can read active services" on public.services;
create policy "Public can read active services" on public.services for select to anon, authenticated using (active = true or public.is_admin());
drop policy if exists "Admins manage services" on public.services;
create policy "Admins manage services" on public.services for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins manage service orders" on public.service_orders;
create policy "Admins manage service orders" on public.service_orders for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read active banners" on public.banners;
create policy "Public can read active banners" on public.banners for select to anon, authenticated
using (active = true and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at >= now()) or public.is_admin());
drop policy if exists "Admins manage banners" on public.banners;
create policy "Admins manage banners" on public.banners for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read store settings" on public.store_settings;
create policy "Public can read store settings" on public.store_settings for select to anon, authenticated using (id = 1);
drop policy if exists "Admins manage store settings" on public.store_settings;
create policy "Admins manage store settings" on public.store_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant select, insert, update, delete on public.orders to authenticated;
grant usage, select on sequence public.orders_id_seq to authenticated;
grant select on public.services, public.banners, public.store_settings to anon, authenticated;
grant insert, update, delete on public.services, public.service_orders, public.banners, public.store_settings to authenticated;
grant select on public.service_orders to authenticated;
grant usage, select on sequence public.services_id_seq, public.service_orders_id_seq, public.banners_id_seq to authenticated;

commit;
