begin;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  icon text not null default '◇',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_unique unique (name),
  constraint categories_slug_unique unique (slug)
);

insert into public.categories (name, slug, sort_order)
select
  source.category,
  lower(regexp_replace(regexp_replace(trim(source.category), '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')),
  row_number() over (order by source.category)::integer
from (
  select distinct trim(category) as category
  from public.products
  where nullif(trim(category), '') is not null
) source
on conflict do nothing;

alter table public.categories enable row level security;

drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
on public.categories for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins manage categories" on public.categories;
create policy "Admins manage categories"
on public.categories for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;
grant insert, update, delete on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

create or replace function public.admin_rename_category(category_id bigint, new_name text)
returns public.categories
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_category public.categories;
  renamed_category public.categories;
  clean_name text := trim(new_name);
  clean_slug text;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if clean_name = '' then
    raise exception 'category_name_required' using errcode = '22023';
  end if;

  select * into current_category from public.categories where id = category_id;
  if not found then
    raise exception 'category_not_found' using errcode = 'P0002';
  end if;

  clean_slug := lower(regexp_replace(regexp_replace(clean_name, '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g'));

  update public.categories
  set name = clean_name, slug = clean_slug
  where id = category_id
  returning * into renamed_category;

  update public.products
  set category = clean_name
  where category = current_category.name;

  return renamed_category;
end;
$$;

create or replace function public.admin_delete_category(category_id bigint)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  category_name text;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  select name into category_name from public.categories where id = category_id;
  if not found then
    raise exception 'category_not_found' using errcode = 'P0002';
  end if;

  if exists (select 1 from public.products where category = category_name) then
    raise exception 'category_in_use' using errcode = '23503';
  end if;

  delete from public.categories where id = category_id;
end;
$$;

revoke all on function public.admin_rename_category(bigint, text) from public;
grant execute on function public.admin_rename_category(bigint, text) to authenticated;
revoke all on function public.admin_delete_category(bigint) from public;
grant execute on function public.admin_delete_category(bigint) to authenticated;

commit;
