-- Apply after supabase-schema.sql, admin-001-auth-dashboard.sql and admin-004-operations-management.sql.
-- Run once in the Supabase SQL editor before enabling storefront checkout.
begin;

-- Keep existing orders and admin workflows; move storefront writes behind RPCs.
alter table public.products add column if not exists sku text;
update public.products set sku = 'BIG-' || id where sku is null or btrim(sku) = '';
create unique index if not exists products_sku_unique on public.products(sku);

alter table public.store_settings
  add column if not exists delivery_checkout_enabled boolean not null default false;

alter table public.orders
  add column if not exists order_number text,
  add column if not exists customer_id uuid references auth.users(id) on delete set null,
  add column if not exists subtotal numeric(12,2),
  add column if not exists discount_total numeric(12,2) not null default 0,
  add column if not exists shipping_total numeric(12,2) not null default 0,
  add column if not exists coupon_code text,
  add column if not exists delivery_address jsonb,
  add column if not exists payment_method text,
  add column if not exists delivery_method text,
  add column if not exists payment_status text not null default 'pending',
  add column if not exists tracking_token uuid not null default gen_random_uuid(),
  add column if not exists idempotency_key uuid,
  add column if not exists stock_reserved boolean not null default false,
  add column if not exists stock_released boolean not null default false;
create unique index if not exists orders_order_number_unique on public.orders(order_number);
create unique index if not exists orders_idempotency_unique on public.orders(idempotency_key);
update public.orders set order_number = 'BIG-' || lpad(id::text, 8, '0') where order_number is null;
update public.orders set subtotal = total where subtotal is null;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'orders_payment_status_check') then
    alter table public.orders add constraint orders_payment_status_check check (payment_status in ('pending','paid','failed','cancelled','refunded'));
  end if;
end $$;

create table if not exists public.checkout_coupons (
  code text primary key check (code = upper(code) and length(code) between 3 and 40),
  active boolean not null default true,
  discount_type text not null check (discount_type in ('percent','fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  minimum_subtotal numeric(12,2) not null default 0 check (minimum_subtotal >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  max_uses integer check (max_uses is null or max_uses > 0),
  max_uses_per_customer integer check (max_uses_per_customer is null or max_uses_per_customer > 0),
  used_count integer not null default 0 check (used_count >= 0),
  allowed_product_ids bigint[],
  allowed_categories text[],
  created_at timestamptz not null default now(),
  check (discount_type <> 'percent' or discount_value <= 100),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);
alter table public.checkout_coupons enable row level security;

create table if not exists public.checkout_payment_methods (
  code text primary key,
  label text not null,
  active boolean not null default false,
  integration_mode text not null default 'manual_pending' check (integration_mode in ('manual_pending','gateway')),
  created_at timestamptz not null default now()
);
alter table public.checkout_payment_methods enable row level security;
insert into public.checkout_payment_methods(code,label,active,integration_mode)
values ('pix','PIX',true,'manual_pending'),('cartao','Cartão de crédito',true,'manual_pending')
on conflict (code) do nothing;
drop policy if exists "Public can read checkout payment methods" on public.checkout_payment_methods;
create policy "Public can read checkout payment methods" on public.checkout_payment_methods
  for select to anon, authenticated using (active);

drop policy if exists "Admins manage checkout coupons" on public.checkout_coupons;
create policy "Admins manage checkout coupons" on public.checkout_coupons
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins manage checkout payment methods" on public.checkout_payment_methods;
create policy "Admins manage checkout payment methods" on public.checkout_payment_methods
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
grant select, insert, update, delete on public.checkout_coupons to authenticated;
grant insert, update, delete on public.checkout_payment_methods to authenticated;
create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Endereço',
  cep text not null,
  street text not null,
  number text not null,
  complement text,
  neighborhood text not null,
  city text not null,
  state text not null,
  reference text,
  created_at timestamptz not null default now()
);
alter table public.customer_addresses enable row level security;
drop policy if exists "Customers manage own addresses" on public.customer_addresses;
create policy "Customers manage own addresses" on public.customer_addresses
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create table if not exists public.customer_carts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  items jsonb not null default '{}'::jsonb check (jsonb_typeof(items) = 'object'),
  updated_at timestamptz not null default now()
);
alter table public.customer_carts enable row level security;
drop policy if exists "Customers manage own carts" on public.customer_carts;
create policy "Customers manage own carts" on public.customer_carts
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "Customers can read own orders" on public.orders;
create policy "Customers can read own orders" on public.orders
  for select to authenticated using (customer_id = auth.uid());
grant select on public.orders to authenticated;
-- The old public INSERT accepted client supplied prices, totals and status.
drop policy if exists "Public can create orders" on public.orders;
revoke insert on public.orders from anon;
grant insert on public.orders to authenticated;
revoke usage on sequence public.orders_id_seq from anon;
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.customer_addresses, public.customer_carts to authenticated;
grant usage, select on sequence public.customer_addresses_id_seq to authenticated;
grant select on public.checkout_payment_methods to anon, authenticated;
revoke all on public.checkout_coupons from anon;

create or replace function public.checkout_calculate(
  p_items jsonb, p_coupon text, p_delivery_method text, p_lock boolean default false
) returns jsonb
language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  entry jsonb;
  item record;
  product_row public.products%rowtype;
  coupon_row public.checkout_coupons%rowtype;
  settings_row public.store_settings%rowtype;
  seen bigint[] := '{}';
  snapshot jsonb := '[]'::jsonb;
  subtotal numeric(12,2) := 0;
  eligible numeric(12,2) := 0;
  discount_total numeric(12,2) := 0;
  shipping_total numeric(12,2) := 0;
  quantity integer;
  normalized_coupon text := nullif(upper(btrim(coalesce(p_coupon,''))), '');
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 50 then
    raise exception 'Carrinho inválido.';
  end if;
  if p_delivery_method not in ('entrega','retirada') then
    raise exception 'Escolha uma forma de entrega.';
  end if;
  for item in
    select (value->>'product_id')::bigint as product_id, value
    from jsonb_array_elements(p_items) as value
    order by (value->>'product_id')::bigint
  loop
    entry := item.value;
    if item.product_id is null or item.product_id = any(seen)
       or (entry->>'quantity') !~ '^[1-9][0-9]{0,3}$' then
      raise exception 'Item ou quantidade inválida.';
    end if;
    seen := array_append(seen,item.product_id);
    quantity := (entry->>'quantity')::integer;
    if p_lock then
      select * into product_row from public.products where id = item.product_id for update;
    else
      select * into product_row from public.products where id = item.product_id;
    end if;
    if not found or not product_row.active then
      raise exception 'Produto indisponível: %', item.product_id;
    end if;
    if product_row.stock < quantity then
      raise exception 'Estoque insuficiente: % (disponível: %)', product_row.name, product_row.stock;
    end if;
    subtotal := subtotal + product_row.price * quantity;
    snapshot := snapshot || jsonb_build_array(jsonb_build_object(
      'product_id', product_row.id, 'name', product_row.name, 'sku', coalesce(product_row.sku,'BIG-' || product_row.id),
      'image_url', product_row.image_url, 'quantity', quantity,
      'unit_price', product_row.price, 'subtotal', product_row.price * quantity
    ));
  end loop;
  if normalized_coupon is not null then
    if p_lock then
      select * into coupon_row from public.checkout_coupons where code = normalized_coupon for update;
    else
      select * into coupon_row from public.checkout_coupons where code = normalized_coupon;
    end if;
    if not found or not coupon_row.active then raise exception 'Cupom inválido.'; end if;
    if coupon_row.starts_at is not null and now() < coupon_row.starts_at then raise exception 'Cupom ainda não está válido.'; end if;
    if coupon_row.ends_at is not null and now() > coupon_row.ends_at then raise exception 'Cupom expirado.'; end if;
    if coupon_row.max_uses is not null and coupon_row.used_count >= coupon_row.max_uses then raise exception 'Cupom esgotado.'; end if;
    if subtotal < coupon_row.minimum_subtotal then raise exception 'Valor mínimo do cupom não atingido.'; end if;
    if coupon_row.max_uses_per_customer is not null then
      if auth.uid() is null then raise exception 'Entre na sua conta para usar este cupom.'; end if;
      if (select count(*) from public.orders
          where customer_id = auth.uid() and coupon_code = normalized_coupon
          and payment_status not in ('failed','cancelled')) >= coupon_row.max_uses_per_customer then
        raise exception 'Limite do cupom por cliente atingido.';
      end if;
    end if;
    select coalesce(sum((value->>'subtotal')::numeric),0) into eligible
    from jsonb_array_elements(snapshot) as value
    join public.products p on p.id = (value->>'product_id')::bigint
    where (coupon_row.allowed_product_ids is null or p.id = any(coupon_row.allowed_product_ids))
      and (coupon_row.allowed_categories is null or p.category = any(coupon_row.allowed_categories));
    if eligible <= 0 then raise exception 'Cupom não se aplica aos produtos do carrinho.'; end if;
    discount_total := least(eligible,
      case when coupon_row.discount_type = 'percent'
        then round(eligible * coupon_row.discount_value / 100, 2)
        else coupon_row.discount_value end);
  end if;
  if p_delivery_method = 'entrega' then
    select * into settings_row from public.store_settings where id = 1;
    if not found or not settings_row.delivery_checkout_enabled then
      raise exception 'Entrega ainda não está disponível no checkout. Escolha retirada na loja.';
    end if;
    shipping_total := case
      when settings_row.free_shipping_min > 0 and subtotal - discount_total >= settings_row.free_shipping_min then 0
      else settings_row.delivery_fee end;
  end if;
  return jsonb_build_object('items',snapshot,'subtotal',subtotal,'discount_total',discount_total,
    'shipping_total',shipping_total,'total',subtotal-discount_total+shipping_total,
    'coupon_code',normalized_coupon,'delivery_method',p_delivery_method);
end;
$$;
revoke all on function public.checkout_calculate(jsonb,text,text,boolean) from public, anon, authenticated;

create or replace function public.checkout_quote(
  p_items jsonb, p_coupon text, p_delivery_method text
) returns jsonb
language sql security definer
set search_path = public, pg_temp
as $$
  select public.checkout_calculate(p_items,p_coupon,p_delivery_method,false)
$$;
revoke all on function public.checkout_quote(jsonb,text,text) from public;
grant execute on function public.checkout_quote(jsonb,text,text) to anon, authenticated;

create or replace function public.checkout_place_order(
  p_items jsonb, p_coupon text, p_delivery_method text, p_payment_method text,
  p_customer jsonb, p_address jsonb, p_idempotency_key uuid, p_expected_total numeric
) returns jsonb
language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  quote jsonb;
  existing public.orders%rowtype;
  placed public.orders%rowtype;
  item jsonb;
  method_row public.checkout_payment_methods%rowtype;
  safe_address jsonb;
begin
  if p_idempotency_key is null then raise exception 'Identificador da tentativa obrigatório.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key::text,0));
  select * into existing from public.orders where idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('order_number',existing.order_number,'tracking_token',existing.tracking_token,
      'items',existing.items,'subtotal',existing.subtotal,'discount_total',existing.discount_total,
      'shipping_total',existing.shipping_total,'total',existing.total,'status',existing.status,
      'payment_status',existing.payment_status,'delivery_method',existing.delivery_method,
      'payment_method',existing.payment_method);
  end if;
  if length(btrim(coalesce(p_customer->>'name',''))) < 2
     or coalesce(p_customer->>'email','') !~ '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'
     or length(regexp_replace(coalesce(p_customer->>'phone',''),'[^0-9]','','g')) not between 10 and 11 then
    raise exception 'Dados do cliente inválidos.';
  end if;
  select * into method_row from public.checkout_payment_methods where code = p_payment_method and active;
  if not found then raise exception 'Forma de pagamento indisponível.'; end if;
  if p_delivery_method = 'entrega' then
    if length(regexp_replace(coalesce(p_address->>'cep',''),'[^0-9]','','g')) <> 8
       or length(btrim(coalesce(p_address->>'street',''))) < 2
       or length(btrim(coalesce(p_address->>'number',''))) < 1
       or length(btrim(coalesce(p_address->>'neighborhood',''))) < 2
       or length(btrim(coalesce(p_address->>'city',''))) < 2
       or coalesce(p_address->>'state','') !~ '^[A-Z]{2}$' then
      raise exception 'Endereço de entrega incompleto.';
    end if;
    safe_address := jsonb_build_object(
      'cep',p_address->>'cep','street',p_address->>'street','number',p_address->>'number',
      'complement',p_address->>'complement','neighborhood',p_address->>'neighborhood',
      'city',p_address->>'city','state',p_address->>'state','reference',p_address->>'reference');
  else
    safe_address := null;
  end if;
  quote := public.checkout_calculate(p_items,p_coupon,p_delivery_method,true);
  if p_expected_total is null or p_expected_total <> (quote->>'total')::numeric then
    raise exception 'Valores atualizados. Revise o pedido antes de confirmar.';
  end if;
  insert into public.orders(customer_id,customer_name,customer_email,customer_phone,items,
    subtotal,discount_total,shipping_total,total,coupon_code,delivery_method,delivery_address,
    payment_method,payment_status,status,idempotency_key,stock_reserved)
  values (auth.uid(),btrim(p_customer->>'name'),btrim(p_customer->>'email'),btrim(p_customer->>'phone'),
    quote->'items',(quote->>'subtotal')::numeric,(quote->>'discount_total')::numeric,
    (quote->>'shipping_total')::numeric,(quote->>'total')::numeric,
    quote->>'coupon_code',p_delivery_method,safe_address,p_payment_method,'pending','recebido',p_idempotency_key,true)
  returning * into placed;
  update public.orders set order_number = 'BIG-' || lpad(placed.id::text,8,'0')
    where id = placed.id returning * into placed;
  for item in select value from jsonb_array_elements(quote->'items') as value loop
    update public.products set stock = stock - (item->>'quantity')::integer
      where id = (item->>'product_id')::bigint and stock >= (item->>'quantity')::integer;
    if not found then raise exception 'Estoque insuficiente: %', item->>'name'; end if;
  end loop;
  if (quote->>'coupon_code') is not null then
    update public.checkout_coupons set used_count = used_count + 1 where code = quote->>'coupon_code';
  end if;
  return jsonb_build_object('order_number',placed.order_number,'tracking_token',placed.tracking_token,
    'items',placed.items,'subtotal',placed.subtotal,'discount_total',placed.discount_total,
    'shipping_total',placed.shipping_total,'total',placed.total,'status',placed.status,
    'payment_status',placed.payment_status,'delivery_method',placed.delivery_method,
    'payment_method',placed.payment_method);
end;
$$;
revoke all on function public.checkout_place_order(jsonb,text,text,text,jsonb,jsonb,uuid,numeric) from public;
grant execute on function public.checkout_place_order(jsonb,text,text,text,jsonb,jsonb,uuid,numeric) to anon, authenticated;

create or replace function public.checkout_get_order(p_order_number text,p_tracking_token uuid)
returns jsonb
language sql security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object('order_number',order_number,'items',items,'subtotal',subtotal,
    'discount_total',discount_total,'shipping_total',shipping_total,'total',total,
    'status',status,'payment_status',payment_status,'delivery_method',delivery_method,
    'payment_method',payment_method,'created_at',created_at)
  from public.orders
  where order_number = p_order_number and tracking_token = p_tracking_token
  limit 1
$$;
revoke all on function public.checkout_get_order(text,uuid) from public;
grant execute on function public.checkout_get_order(text,uuid) to anon, authenticated;

-- A pending order reserves stock. Releasing a cancelled/failed order happens once.
create or replace function public.checkout_release_stock()
returns trigger language plpgsql security definer
set search_path = public, pg_temp
as $$
declare item jsonb;
begin
  if not old.stock_reserved then return new; end if;
  if new.status = 'pago' and old.status is distinct from 'pago' then
    new.payment_status := 'paid';
  end if;
  if new.status = 'cancelado' and new.payment_status = 'pending' then
    new.payment_status := 'cancelled';
  end if;
  if new.payment_status in ('failed','cancelled') then
    new.status := 'cancelado';
  end if;
  if old.stock_released then
    if new.payment_status = 'paid' or new.status in ('pago','em_preparacao','pronto','concluido') then
      raise exception 'Pedido cancelado não pode ser reativado sem nova reserva de estoque.';
    end if;
    new.stock_released := true;
    return new;
  end if;
  if new.status = 'cancelado' or new.payment_status in ('failed','cancelled') then
    for item in select value from jsonb_array_elements(new.items) as value loop
      update public.products set stock = stock + (item->>'quantity')::integer
        where id = (item->>'product_id')::bigint;
    end loop;
    if new.coupon_code is not null then
      update public.checkout_coupons set used_count = greatest(0,used_count-1)
        where code = new.coupon_code;
    end if;
    new.stock_released := true;
  end if;
  return new;
end;
$$;
drop trigger if exists checkout_release_stock_trigger on public.orders;
create trigger checkout_release_stock_trigger before update of status,payment_status on public.orders
for each row execute function public.checkout_release_stock();

commit;
