-- BLACKOUT INFOR GAMES — catálogo de consoles e variantes genéricas.
-- Execute após supabase-schema.sql, admin-001 e commerce-001.
begin;

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  option_name text not null check (length(btrim(option_name)) between 1 and 60),
  option_value text not null check (length(btrim(option_value)) between 1 and 80),
  price numeric(12,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  sku text not null unique,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, option_name, option_value)
);

alter table public.product_variants enable row level security;
drop policy if exists "Public can read active product variants" on public.product_variants;
create policy "Public can read active product variants" on public.product_variants
for select to anon, authenticated
using (active and exists (select 1 from public.products p where p.id=product_id and p.active));
drop policy if exists "Admins manage product variants" on public.product_variants;
create policy "Admins manage product variants" on public.product_variants
for all to authenticated using (public.is_admin()) with check (public.is_admin());
grant select on public.product_variants to anon, authenticated;
grant insert, update, delete on public.product_variants to authenticated;
grant usage, select on sequence public.product_variants_id_seq to authenticated;

create or replace function public.sync_variant_product_totals(p_product_id bigint)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if exists(select 1 from public.product_variants where product_id=p_product_id) then
    update public.products set
      price=coalesce((select min(price) from public.product_variants where product_id=p_product_id and active),price),
      old_price=greatest(old_price,coalesce((select min(price) from public.product_variants where product_id=p_product_id and active),price)),
      stock=coalesce((select sum(stock) from public.product_variants where product_id=p_product_id and active),0),
      updated_at=now()
    where id=p_product_id;
  end if;
end;
$$;

create or replace function public.product_variants_after_change()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
  perform public.sync_variant_product_totals(coalesce(new.product_id,old.product_id));
  if tg_op='UPDATE' and new.product_id is distinct from old.product_id then
    perform public.sync_variant_product_totals(old.product_id);
  end if;
  return coalesce(new,old);
end;
$$;
drop trigger if exists product_variants_sync_product on public.product_variants;
create trigger product_variants_sync_product after insert or update or delete on public.product_variants
for each row execute function public.product_variants_after_change();

do $$
declare ps4_id bigint; switch_id bigint; ps2_id bigint;
begin
  select id into ps4_id from public.products
  where (lower(name) like '%playstation 4%' or lower(name) like '%ps4%') and lower(name) like '%slim%'
  order by id limit 1;
  if ps4_id is null then
    insert into public.products(name,category,platform,price,old_price,discount,image_url,icon,glow,stock,stock_min,brand,rating,description,active,sku)
    values('PlayStation 4 Slim','Consoles','PlayStation 4',1500,1500,0,'./assets/console-ps4-slim-mobile.jpg','🎮','#00a8ff',3,1,'PlayStation',null,'Desempenho, catálogo de grandes jogos e entretenimento em um design compacto.',true,'BIG-PS4-SLIM')
    returning id into ps4_id;
  else
    update public.products set name='PlayStation 4 Slim',category='Consoles',platform='PlayStation 4',price=1500,old_price=1500,
      discount=0,image_url='./assets/console-ps4-slim-mobile.jpg',icon='🎮',glow='#00a8ff',stock=3,stock_min=1,
      brand='PlayStation',description='Desempenho, catálogo de grandes jogos e entretenimento em um design compacto.',active=true,sku='BIG-PS4-SLIM',updated_at=now()
    where id=ps4_id;
  end if;

  select id into switch_id from public.products where lower(name) like '%nintendo switch lite%' order by id limit 1;
  if switch_id is null then
    insert into public.products(name,category,platform,price,old_price,discount,image_url,icon,glow,stock,stock_min,brand,rating,description,active,sku)
    values('Nintendo Switch Lite','Consoles','Nintendo Switch',1300,1300,0,'./assets/console-switch-lite-mobile.jpg','🎮','#ff342e',2,1,'Nintendo',null,'Leve, portátil e pronto para jogar onde você quiser.',true,'BIG-SWITCH-LITE')
    returning id into switch_id;
  else
    update public.products set name='Nintendo Switch Lite',category='Consoles',platform='Nintendo Switch',price=1300,old_price=1300,
      discount=0,image_url='./assets/console-switch-lite-mobile.jpg',icon='🎮',glow='#ff342e',stock=2,stock_min=1,
      brand='Nintendo',description='Leve, portátil e pronto para jogar onde você quiser.',active=true,sku='BIG-SWITCH-LITE',updated_at=now()
    where id=switch_id;
  end if;

  select id into ps2_id from public.products
  where (lower(name) like '%playstation 2%' or lower(name) like '%ps2%') and lower(name) like '%slim%'
  order by id limit 1;
  if ps2_id is null then
    insert into public.products(name,category,platform,price,old_price,discount,image_url,icon,glow,stock,stock_min,brand,rating,description,active,sku)
    values('PlayStation 2 Slim','Consoles','PlayStation 2',400,400,0,'./assets/console-ps2-slim-mobile.jpg','🎮','#00a8ff',3,1,'PlayStation',null,'Compacto e pronto para jogar. Acompanha 1 controle, Memory Card e pendrive 16 GB com jogos.',true,'BIG-PS2-SLIM')
    returning id into ps2_id;
  else
    update public.products set name='PlayStation 2 Slim',category='Consoles',platform='PlayStation 2',price=400,old_price=400,
      discount=0,image_url='./assets/console-ps2-slim-mobile.jpg',icon='🎮',glow='#00a8ff',stock=3,stock_min=1,
      brand='PlayStation',description='Compacto e pronto para jogar. Acompanha 1 controle, Memory Card e pendrive 16 GB com jogos.',active=true,sku='BIG-PS2-SLIM',updated_at=now()
    where id=ps2_id;
  end if;

  insert into public.product_variants(product_id,option_name,option_value,price,stock,sku,active,sort_order) values
    (ps4_id,'Armazenamento','500 GB',1500,2,'BIG-PS4-SLIM-500GB',true,1),
    (ps4_id,'Armazenamento','1 TB',1700,1,'BIG-PS4-SLIM-1TB',true,2)
  on conflict(product_id,option_name,option_value) do update set price=excluded.price,stock=excluded.stock,sku=excluded.sku,
    active=excluded.active,sort_order=excluded.sort_order,updated_at=now();
  update public.product_variants set active=false,updated_at=now()
  where product_id=ps4_id and (option_name,option_value) not in (('Armazenamento','500 GB'),('Armazenamento','1 TB'));
  update public.products set active=false,updated_at=now()
  where category='Consoles' and id not in(ps4_id,switch_id,ps2_id);
  perform public.sync_variant_product_totals(ps4_id);
end;
$$;

create or replace function public.checkout_calculate(p_items jsonb,p_coupon text,p_delivery_method text,p_lock boolean default false)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
  entry jsonb; item record; product_row public.products%rowtype; variant_row public.product_variants%rowtype;
  coupon_row public.checkout_coupons%rowtype; settings_row public.store_settings%rowtype;
  seen text[]:='{}'; line_key text; snapshot jsonb:='[]'::jsonb; subtotal numeric(12,2):=0;
  eligible numeric(12,2):=0; discount_total numeric(12,2):=0; shipping_total numeric(12,2):=0;
  unit_price numeric(12,2); available_stock integer; quantity integer; has_variants boolean;
  normalized_coupon text:=nullif(upper(btrim(coalesce(p_coupon,''))),'');
begin
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)<1 or jsonb_array_length(p_items)>50 then raise exception 'Carrinho inválido.'; end if;
  if p_delivery_method not in('entrega','retirada') then raise exception 'Escolha uma forma de entrega.'; end if;
  for item in select case when value->>'product_id'~'^[1-9][0-9]*$' then (value->>'product_id')::bigint end product_id,
      case when value->>'variant_id'~'^[1-9][0-9]*$' then (value->>'variant_id')::bigint end variant_id,value
    from jsonb_array_elements(p_items) value order by 1,2 nulls first loop
    entry:=item.value;
    if item.product_id is null or (entry?'variant_id' and item.variant_id is null) or (entry->>'quantity')!~'^[1-9][0-9]{0,3}$' then raise exception 'Item, variante ou quantidade inválida.'; end if;
    line_key:=item.product_id::text||':'||coalesce(item.variant_id::text,'0');
    if line_key=any(seen) then raise exception 'Item repetido no carrinho.'; end if;
    seen:=array_append(seen,line_key); quantity:=(entry->>'quantity')::integer;
    if p_lock then select * into product_row from public.products where id=item.product_id for update;
    else select * into product_row from public.products where id=item.product_id; end if;
    if not found or not product_row.active then raise exception 'Produto indisponível: %',item.product_id; end if;
    select exists(select 1 from public.product_variants where product_id=item.product_id) into has_variants;
    if has_variants then
      if item.variant_id is null then raise exception 'Escolha uma opção para %.',product_row.name; end if;
      if p_lock then select * into variant_row from public.product_variants where id=item.variant_id and product_id=item.product_id and active for update;
      else select * into variant_row from public.product_variants where id=item.variant_id and product_id=item.product_id and active; end if;
      if not found then raise exception 'Opção indisponível para %.',product_row.name; end if;
      unit_price:=variant_row.price; available_stock:=variant_row.stock;
    else
      if item.variant_id is not null then raise exception 'Variante inválida para %.',product_row.name; end if;
      unit_price:=product_row.price; available_stock:=product_row.stock;
    end if;
    if available_stock<quantity then raise exception 'Estoque insuficiente: % (disponível: %)',product_row.name,available_stock; end if;
    subtotal:=subtotal+unit_price*quantity;
    snapshot:=snapshot||jsonb_build_array(jsonb_build_object('product_id',product_row.id,
      'variant_id',case when has_variants then variant_row.id else null end,'name',product_row.name,
      'variant_name',case when has_variants then variant_row.option_name else null end,
      'variant_value',case when has_variants then variant_row.option_value else null end,
      'sku',case when has_variants then variant_row.sku else coalesce(product_row.sku,'BIG-'||product_row.id) end,
      'image_url',product_row.image_url,'quantity',quantity,'unit_price',unit_price,'subtotal',unit_price*quantity));
  end loop;
  if normalized_coupon is not null then
    if p_lock then select * into coupon_row from public.checkout_coupons where code=normalized_coupon for update;
    else select * into coupon_row from public.checkout_coupons where code=normalized_coupon; end if;
    if not found or not coupon_row.active then raise exception 'Cupom inválido.'; end if;
    if coupon_row.starts_at is not null and now()<coupon_row.starts_at then raise exception 'Cupom ainda não está válido.'; end if;
    if coupon_row.ends_at is not null and now()>coupon_row.ends_at then raise exception 'Cupom expirado.'; end if;
    if coupon_row.max_uses is not null and coupon_row.used_count>=coupon_row.max_uses then raise exception 'Cupom esgotado.'; end if;
    if subtotal<coupon_row.minimum_subtotal then raise exception 'Valor mínimo do cupom não atingido.'; end if;
    if coupon_row.max_uses_per_customer is not null then
      if auth.uid() is null then raise exception 'Entre na sua conta para usar este cupom.'; end if;
      if (select count(*) from public.orders where customer_id=auth.uid() and coupon_code=normalized_coupon and payment_status not in('failed','cancelled'))>=coupon_row.max_uses_per_customer then raise exception 'Limite do cupom por cliente atingido.'; end if;
    end if;
    select coalesce(sum((value->>'subtotal')::numeric),0) into eligible from jsonb_array_elements(snapshot) value
    join public.products p on p.id=(value->>'product_id')::bigint
    where (coupon_row.allowed_product_ids is null or p.id=any(coupon_row.allowed_product_ids))
      and (coupon_row.allowed_categories is null or p.category=any(coupon_row.allowed_categories));
    if eligible<=0 then raise exception 'Cupom não se aplica aos produtos do carrinho.'; end if;
    discount_total:=least(eligible,case when coupon_row.discount_type='percent' then round(eligible*coupon_row.discount_value/100,2) else coupon_row.discount_value end);
  end if;
  if p_delivery_method='entrega' then
    select * into settings_row from public.store_settings where id=1;
    if not found or not settings_row.delivery_checkout_enabled then raise exception 'Entrega ainda não está disponível no checkout. Escolha retirada na loja.'; end if;
    shipping_total:=case when settings_row.free_shipping_min>0 and subtotal-discount_total>=settings_row.free_shipping_min then 0 else settings_row.delivery_fee end;
  end if;
  return jsonb_build_object('items',snapshot,'subtotal',subtotal,'discount_total',discount_total,'shipping_total',shipping_total,
    'total',subtotal-discount_total+shipping_total,'coupon_code',normalized_coupon,'delivery_method',p_delivery_method);
end;
$$;
revoke all on function public.checkout_calculate(jsonb,text,text,boolean) from public,anon,authenticated;

create or replace function public.checkout_place_order(p_items jsonb,p_coupon text,p_delivery_method text,p_payment_method text,
  p_customer jsonb,p_address jsonb,p_idempotency_key uuid,p_expected_total numeric)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare quote jsonb; existing public.orders%rowtype; placed public.orders%rowtype; item jsonb;
  method_row public.checkout_payment_methods%rowtype; safe_address jsonb;
begin
  if p_idempotency_key is null then raise exception 'Identificador da tentativa obrigatório.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key::text,0));
  select * into existing from public.orders where idempotency_key=p_idempotency_key;
  if found then return jsonb_build_object('order_number',existing.order_number,'tracking_token',existing.tracking_token,'items',existing.items,
    'subtotal',existing.subtotal,'discount_total',existing.discount_total,'shipping_total',existing.shipping_total,'total',existing.total,
    'status',existing.status,'payment_status',existing.payment_status,'delivery_method',existing.delivery_method,'payment_method',existing.payment_method); end if;
  if length(btrim(coalesce(p_customer->>'name','')))<2 or coalesce(p_customer->>'email','')!~'^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'
    or length(regexp_replace(coalesce(p_customer->>'phone',''),'[^0-9]','','g')) not between 10 and 11 then raise exception 'Dados do cliente inválidos.'; end if;
  select * into method_row from public.checkout_payment_methods where code=p_payment_method and active;
  if not found then raise exception 'Forma de pagamento indisponível.'; end if;
  if p_delivery_method='entrega' then
    if length(regexp_replace(coalesce(p_address->>'cep',''),'[^0-9]','','g'))<>8 or length(btrim(coalesce(p_address->>'street','')))<2
      or length(btrim(coalesce(p_address->>'number','')))<1 or length(btrim(coalesce(p_address->>'neighborhood','')))<2
      or length(btrim(coalesce(p_address->>'city','')))<2 or coalesce(p_address->>'state','')!~'^[A-Z]{2}$' then raise exception 'Endereço de entrega incompleto.'; end if;
    safe_address:=jsonb_build_object('cep',p_address->>'cep','street',p_address->>'street','number',p_address->>'number','complement',p_address->>'complement',
      'neighborhood',p_address->>'neighborhood','city',p_address->>'city','state',p_address->>'state','reference',p_address->>'reference');
  end if;
  quote:=public.checkout_calculate(p_items,p_coupon,p_delivery_method,true);
  if p_expected_total is null or p_expected_total<>(quote->>'total')::numeric then raise exception 'Valores atualizados. Revise o pedido antes de confirmar.'; end if;
  insert into public.orders(customer_id,customer_name,customer_email,customer_phone,items,subtotal,discount_total,shipping_total,total,coupon_code,
    delivery_method,delivery_address,payment_method,payment_status,status,idempotency_key,stock_reserved)
  values(auth.uid(),btrim(p_customer->>'name'),btrim(p_customer->>'email'),btrim(p_customer->>'phone'),quote->'items',(quote->>'subtotal')::numeric,
    (quote->>'discount_total')::numeric,(quote->>'shipping_total')::numeric,(quote->>'total')::numeric,quote->>'coupon_code',p_delivery_method,
    safe_address,p_payment_method,'pending','recebido',p_idempotency_key,true) returning * into placed;
  update public.orders set order_number='BIG-'||lpad(placed.id::text,8,'0') where id=placed.id returning * into placed;
  for item in select value from jsonb_array_elements(quote->'items') value loop
    if item->>'variant_id' is not null then
      update public.product_variants set stock=stock-(item->>'quantity')::integer,updated_at=now()
      where id=(item->>'variant_id')::bigint and product_id=(item->>'product_id')::bigint and active and stock>=(item->>'quantity')::integer;
    else
      update public.products set stock=stock-(item->>'quantity')::integer where id=(item->>'product_id')::bigint and stock>=(item->>'quantity')::integer;
    end if;
    if not found then raise exception 'Estoque insuficiente: %',item->>'name'; end if;
  end loop;
  if quote->>'coupon_code' is not null then update public.checkout_coupons set used_count=used_count+1 where code=quote->>'coupon_code'; end if;
  return jsonb_build_object('order_number',placed.order_number,'tracking_token',placed.tracking_token,'items',placed.items,'subtotal',placed.subtotal,
    'discount_total',placed.discount_total,'shipping_total',placed.shipping_total,'total',placed.total,'status',placed.status,
    'payment_status',placed.payment_status,'delivery_method',placed.delivery_method,'payment_method',placed.payment_method);
end;
$$;
revoke all on function public.checkout_place_order(jsonb,text,text,text,jsonb,jsonb,uuid,numeric) from public;
grant execute on function public.checkout_place_order(jsonb,text,text,text,jsonb,jsonb,uuid,numeric) to anon,authenticated;

create or replace function public.checkout_release_stock()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare item jsonb;
begin
  if not old.stock_reserved then return new; end if;
  if new.status='pago' and old.status is distinct from 'pago' then new.payment_status:='paid'; end if;
  if new.status='cancelado' and new.payment_status='pending' then new.payment_status:='cancelled'; end if;
  if new.payment_status in('failed','cancelled') then new.status:='cancelado'; end if;
  if old.stock_released then
    if new.payment_status='paid' or new.status in('pago','em_preparacao','pronto','concluido') then raise exception 'Pedido cancelado não pode ser reativado sem nova reserva de estoque.'; end if;
    new.stock_released:=true; return new;
  end if;
  if new.status='cancelado' or new.payment_status in('failed','cancelled') then
    for item in select value from jsonb_array_elements(new.items) value loop
      if item->>'variant_id' is not null then
        update public.product_variants set stock=stock+(item->>'quantity')::integer,updated_at=now()
        where id=(item->>'variant_id')::bigint and product_id=(item->>'product_id')::bigint;
      else update public.products set stock=stock+(item->>'quantity')::integer where id=(item->>'product_id')::bigint; end if;
    end loop;
    if new.coupon_code is not null then update public.checkout_coupons set used_count=greatest(0,used_count-1) where code=new.coupon_code; end if;
    new.stock_released:=true;
  end if;
  return new;
end;
$$;
drop trigger if exists checkout_release_stock_trigger on public.orders;
create trigger checkout_release_stock_trigger before update of status,payment_status on public.orders
for each row execute function public.checkout_release_stock();

commit;
