create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  platform text not null default '',
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) not null default 0 check (old_price >= 0),
  discount integer not null default 0 check (discount between 0 and 100),
  image_url text,
  icon text not null default '🎮',
  glow text not null default '#ff641e',
  stock integer not null default 0 check (stock >= 0),
  brand text not null default '',
  rating numeric(2,1),
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  items jsonb not null,
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'recebido',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select using (active = true);

drop policy if exists "Public can create orders" on public.orders;
-- Storefront order creation is handled by commerce-001-secure-checkout.sql RPCs.

grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
-- Direct order INSERT is intentionally not granted to storefront roles.
-- The checkout RPC owns order identifiers.
