begin;

insert into public.products (
  name, category, subcategory, condition, product_status, platform,
  price, old_price, discount, image_url, icon, glow, stock, stock_min,
  brand, rating, description, search_terms, active, sku
)
values
  ('Days Gone','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-days-gone.png','🎮','#087dff',1,1,'Bend Studio',null,'Days Gone para PlayStation 4.','days gone ps4 playstation 4',true,'BIG-GAME-PS4-DAYS-GONE'),
  ('Hogwarts Legacy','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-hogwarts-legacy.png','🎮','#087dff',1,1,'Avalanche Software',null,'Hogwarts Legacy para PlayStation 4.','hogwarts legacy ps4 playstation 4',true,'BIG-GAME-PS4-HOGWARTS-LEGACY'),
  ('Red Dead Redemption II','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-red-dead-redemption-2.png','🎮','#087dff',1,1,'Rockstar Games',null,'Red Dead Redemption II para PlayStation 4.','red dead redemption ii 2 ps4 playstation 4',true,'BIG-GAME-PS4-RDR2'),
  ('Grand Theft Auto V','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-gta-5.png','🎮','#087dff',1,1,'Rockstar Games',null,'Grand Theft Auto V para PlayStation 4.','grand theft auto v 5 gta ps4 playstation 4',true,'BIG-GAME-PS4-GTA5'),
  ('Far Cry 4','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-far-cry-4.png','🎮','#087dff',1,1,'Ubisoft',null,'Far Cry 4 para PlayStation 4.','far cry 4 ps4 playstation 4',true,'BIG-GAME-PS4-FAR-CRY-4'),
  ('Far Cry 6','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-far-cry-6.png','🎮','#087dff',1,1,'Ubisoft',null,'Far Cry 6 para PlayStation 4.','far cry 6 ps4 playstation 4',true,'BIG-GAME-PS4-FAR-CRY-6'),
  ('Marvel''s Spider-Man: Game of the Year Edition','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-marvel-spider-man-goty.png','🎮','#087dff',1,1,'Insomniac Games',null,'Marvel''s Spider-Man: Game of the Year Edition para PlayStation 4.','marvel spider man game of the year edition goty ps4 playstation 4',true,'BIG-GAME-PS4-SPIDER-MAN-GOTY'),
  ('Star Wars Jedi: Fallen Order','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-star-wars-jedi-fallen-order.png','🎮','#087dff',1,1,'Respawn Entertainment',null,'Star Wars Jedi: Fallen Order para PlayStation 4.','star wars jedi fallen order ps4 playstation 4',true,'BIG-GAME-PS4-JEDI-FALLEN-ORDER'),
  ('Mortal Kombat 11','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-mortal-kombat-11.png','🎮','#087dff',1,1,'NetherRealm Studios',null,'Mortal Kombat 11 para PlayStation 4.','mortal kombat 11 mk11 ps4 playstation 4',true,'BIG-GAME-PS4-MK11'),
  ('Control','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-control.png','🎮','#087dff',1,1,'Remedy Entertainment',null,'Control para PlayStation 4.','control ps4 playstation 4',true,'BIG-GAME-PS4-CONTROL'),
  ('Watch Dogs: Legion','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-watch-dogs-legion.png','🎮','#087dff',1,1,'Ubisoft',null,'Watch Dogs: Legion para PlayStation 4.','watch dogs legion ps4 playstation 4',true,'BIG-GAME-PS4-WATCH-DOGS-LEGION'),
  ('Back 4 Blood','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-back-4-blood.png','🎮','#087dff',1,1,'Turtle Rock Studios',null,'Back 4 Blood para PlayStation 4.','back 4 blood ps4 playstation 4',true,'BIG-GAME-PS4-BACK-4-BLOOD'),
  ('Immortals Fenyx Rising','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-immortals-fenyx-rising.png','🎮','#087dff',1,1,'Ubisoft',null,'Immortals Fenyx Rising para PlayStation 4.','immortals fenyx rising ps4 playstation 4',true,'BIG-GAME-PS4-IMMORTALS-FENYX'),
  ('Tony Hawk''s Pro Skater 1 + 2','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-tony-hawks-pro-skater-1-2.png','🎮','#087dff',1,1,'Activision',null,'Tony Hawk''s Pro Skater 1 + 2 para PlayStation 4.','tony hawk pro skater 1 2 ps4 playstation 4',true,'BIG-GAME-PS4-THPS-1-2'),
  ('Uncharted: The Nathan Drake Collection','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-uncharted-nathan-drake-collection.png','🎮','#087dff',1,1,'Naughty Dog',null,'Uncharted: The Nathan Drake Collection para PlayStation 4.','uncharted nathan drake collection ps4 playstation 4',true,'BIG-GAME-PS4-UNCHARTED-NATHAN-DRAKE'),
  ('Uncharted 4: A Thief''s End','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-uncharted-4.png','🎮','#087dff',1,1,'Naughty Dog',null,'Uncharted 4: A Thief''s End para PlayStation 4.','uncharted 4 a thief end ps4 playstation 4',true,'BIG-GAME-PS4-UNCHARTED-4'),
  ('Uncharted: The Lost Legacy','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-uncharted-lost-legacy.png','🎮','#087dff',1,1,'Naughty Dog',null,'Uncharted: The Lost Legacy para PlayStation 4.','uncharted the lost legacy ps4 playstation 4',true,'BIG-GAME-PS4-UNCHARTED-LOST-LEGACY'),
  ('Nioh 2','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-nioh-2.png','🎮','#087dff',1,1,'Team Ninja',null,'Nioh 2 para PlayStation 4.','nioh 2 ps4 playstation 4',true,'BIG-GAME-PS4-NIOH-2'),
  ('Darksiders III','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-darksiders-3.png','🎮','#087dff',1,1,'Gunfire Games',null,'Darksiders III para PlayStation 4.','darksiders iii 3 ps4 playstation 4',true,'BIG-GAME-PS4-DARKSIDERS-3'),
  ('Assassin''s Creed Origins','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-assassins-creed-origins.png','🎮','#087dff',1,1,'Ubisoft',null,'Assassin''s Creed Origins para PlayStation 4.','assassins creed origins ps4 playstation 4',true,'BIG-GAME-PS4-AC-ORIGINS'),
  ('Little Nightmares II','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-little-nightmares-2.png','🎮','#087dff',1,1,'Tarsier Studios',null,'Little Nightmares II para PlayStation 4.','little nightmares ii 2 ps4 playstation 4',true,'BIG-GAME-PS4-LITTLE-NIGHTMARES-2'),
  ('Project CARS','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-project-cars.png','🎮','#087dff',1,1,'Slightly Mad Studios',null,'Project CARS para PlayStation 4.','project cars ps4 playstation 4',true,'BIG-GAME-PS4-PROJECT-CARS'),
  ('Need for Speed Heat','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-need-for-speed-heat.png','🎮','#087dff',1,1,'EA',null,'Need for Speed Heat para PlayStation 4.','need for speed heat nfs ps4 playstation 4',true,'BIG-GAME-PS4-NFS-HEAT'),
  ('Horizon Chase Turbo','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-horizon-chase-turbo.png','🎮','#087dff',1,1,'Aquiris Game Studio',null,'Horizon Chase Turbo para PlayStation 4.','horizon chase turbo ps4 playstation 4',true,'BIG-GAME-PS4-HORIZON-CHASE-TURBO'),
  ('Payday 2','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-payday-2.png','🎮','#087dff',1,1,'Starbreeze Studios',null,'Payday 2 para PlayStation 4.','payday 2 ps4 playstation 4',true,'BIG-GAME-PS4-PAYDAY-2'),
  ('Tom Clancy''s Rainbow Six Siege','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-rainbow-six-siege.png','🎮','#087dff',1,1,'Ubisoft',null,'Tom Clancy''s Rainbow Six Siege para PlayStation 4.','tom clancy rainbow six siege r6 ps4 playstation 4',true,'BIG-GAME-PS4-R6-SIEGE'),
  ('Battlefield 2042','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-battlefield-2042.png','🎮','#087dff',1,1,'EA',null,'Battlefield 2042 para PlayStation 4.','battlefield 2042 ps4 playstation 4',true,'BIG-GAME-PS4-BATTLEFIELD-2042'),
  ('Star Wars Battlefront','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-star-wars-battlefront.png','🎮','#087dff',1,1,'EA',null,'Star Wars Battlefront para PlayStation 4.','star wars battlefront ps4 playstation 4',true,'BIG-GAME-PS4-STAR-WARS-BATTLEFRONT'),
  ('LEGO Star Wars','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-lego-star-wars.png','🎮','#087dff',1,1,'TT Games',null,'LEGO Star Wars para PlayStation 4.','lego star wars ps4 playstation 4',true,'BIG-GAME-PS4-LEGO-STAR-WARS'),
  ('LEGO Ninjago','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-lego-ninjago.png','🎮','#087dff',1,1,'TT Games',null,'LEGO Ninjago para PlayStation 4.','lego ninjago ps4 playstation 4',true,'BIG-GAME-PS4-LEGO-NINJAGO'),
  ('LEGO Marvel Super Heroes','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-lego-marvel-super-heroes.png','🎮','#087dff',1,1,'TT Games',null,'LEGO Marvel Super Heroes para PlayStation 4.','lego marvel super heroes ps4 playstation 4',true,'BIG-GAME-PS4-LEGO-MARVEL'),
  ('LEGO Harry Potter Collection','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-lego-harry-potter-collection.png','🎮','#087dff',1,1,'TT Games',null,'LEGO Harry Potter Collection para PlayStation 4.','lego harry potter collection ps4 playstation 4',true,'BIG-GAME-PS4-LEGO-HARRY-POTTER'),
  ('Naruto Shippuden: Ultimate Ninja Storm 4','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-naruto-ultimate-ninja-storm-4.png','🎮','#087dff',1,1,'CyberConnect2',null,'Naruto Shippuden: Ultimate Ninja Storm 4 para PlayStation 4.','naruto shippuden ultimate ninja storm 4 ps4 playstation 4',true,'BIG-GAME-PS4-NARUTO-STORM-4'),
  ('Crash Bandicoot N. Sane Trilogy','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-crash-bandicoot-n-sane-trilogy.png','🎮','#087dff',1,1,'Activision',null,'Crash Bandicoot N. Sane Trilogy para PlayStation 4.','crash bandicoot n sane trilogy ps4 playstation 4',true,'BIG-GAME-PS4-CRASH-NSANE'),
  ('Dragon Ball Xenoverse 2','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-dragon-ball-xenoverse-2.png','🎮','#087dff',1,1,'Bandai Namco',null,'Dragon Ball Xenoverse 2 para PlayStation 4.','dragon ball xenoverse 2 ps4 playstation 4',true,'BIG-GAME-PS4-DB-XENOVERSE-2'),
  ('Batman: Arkham Knight','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-batman-arkham-knight.png','🎮','#087dff',1,1,'Rocksteady Studios',null,'Batman: Arkham Knight para PlayStation 4.','batman arkham knight ps4 playstation 4',true,'BIG-GAME-PS4-BATMAN-ARKHAM-KNIGHT'),
  ('Final Fantasy XV','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-final-fantasy-15.png','🎮','#087dff',1,1,'Square Enix',null,'Final Fantasy XV para PlayStation 4.','final fantasy xv 15 ps4 playstation 4',true,'BIG-GAME-PS4-FINAL-FANTASY-15'),
  ('Destiny','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-destiny.png','🎮','#087dff',1,1,'Bungie',null,'Destiny para PlayStation 4.','destiny ps4 playstation 4',true,'BIG-GAME-PS4-DESTINY'),
  ('The Evil Within 2','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-the-evil-within-2.png','🎮','#087dff',1,1,'Tango Gameworks',null,'The Evil Within 2 para PlayStation 4.','the evil within 2 ps4 playstation 4',true,'BIG-GAME-PS4-EVIL-WITHIN-2'),
  ('PES 2016','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-pes-2016.png','🎮','#087dff',1,1,'Konami',null,'PES 2016 para PlayStation 4.','pes 2016 pro evolution soccer ps4 playstation 4',true,'BIG-GAME-PS4-PES-2016'),
  ('FIFA 19','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-fifa-19.png','🎮','#087dff',1,1,'EA Sports',null,'FIFA 19 para PlayStation 4.','fifa 19 ps4 playstation 4',true,'BIG-GAME-PS4-FIFA-19'),
  ('FIFA 22','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-fifa-22.png','🎮','#087dff',1,1,'EA Sports',null,'FIFA 22 para PlayStation 4.','fifa 22 ps4 playstation 4',true,'BIG-GAME-PS4-FIFA-22'),
  ('South Park: The Fractured But Whole','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-south-park-fractured-but-whole.png','🎮','#087dff',1,1,'Ubisoft',null,'South Park: The Fractured But Whole para PlayStation 4.','south park fractured but whole ps4 playstation 4',true,'BIG-GAME-PS4-SOUTH-PARK-FRACTURED'),
  ('South Park: The Stick of Truth','Jogos','PS4','Novo','Em estoque','PlayStation 4',100,100,0,'./assets/game-ps4-south-park-stick-of-truth.png','🎮','#087dff',1,1,'Ubisoft',null,'South Park: The Stick of Truth para PlayStation 4.','south park stick of truth ps4 playstation 4',true,'BIG-GAME-PS4-SOUTH-PARK-STICK-TRUTH')
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  condition = excluded.condition,
  product_status = excluded.product_status,
  platform = excluded.platform,
  image_url = excluded.image_url,
  icon = excluded.icon,
  glow = excluded.glow,
  brand = excluded.brand,
  description = excluded.description,
  search_terms = excluded.search_terms,
  active = true,
  updated_at = now();

commit;
