-- Migração incremental do painel administrativo final.
begin;

alter table public.products
  add column if not exists publication_status text not null default 'published',
  add column if not exists package_contents text not null default '',
  add column if not exists promotion_starts_at timestamptz,
  add column if not exists promotion_ends_at timestamptz,
  add column if not exists featured boolean not null default false;

alter table public.categories add column if not exists image_url text;
alter table public.banners add column if not exists placement text not null default 'hero';
alter table public.store_settings add column if not exists low_stock_default integer not null default 3;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'products_publication_status_check' and conrelid = 'public.products'::regclass) then
    alter table public.products add constraint products_publication_status_check
      check (publication_status in ('draft','published','inactive'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'products_promotion_schedule_check' and conrelid = 'public.products'::regclass) then
    alter table public.products add constraint products_promotion_schedule_check
      check (promotion_ends_at is null or promotion_starts_at is null or promotion_ends_at > promotion_starts_at);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'store_settings_low_stock_default_check' and conrelid = 'public.store_settings'::regclass) then
    alter table public.store_settings add constraint store_settings_low_stock_default_check check (low_stock_default >= 0);
  end if;
end $$;

update public.products
set publication_status = case when active then 'published' else 'inactive' end
where publication_status is null or publication_status not in ('draft','published','inactive');

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_text text not null default '',
  is_primary boolean not null default false,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  previous_stock integer not null check (previous_stock >= 0),
  new_stock integer not null check (new_stock >= 0),
  delta integer not null,
  reason text not null default 'Ajuste administrativo',
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists product_images_one_primary_idx on public.product_images (product_id) where is_primary;
create index if not exists product_images_product_sort_idx on public.product_images (product_id, sort_order, id);
create index if not exists stock_movements_product_created_idx on public.stock_movements (product_id, created_at desc);
create index if not exists products_admin_updated_idx on public.products (updated_at desc, id desc);
create index if not exists products_active_category_idx on public.products (active, category);
create index if not exists products_low_stock_idx on public.products (stock, stock_min) where active;
create index if not exists products_active_offer_idx on public.products (promotion_ends_at, promotion_starts_at) where active and discount > 0;
create index if not exists banners_active_schedule_idx on public.banners (placement, sort_order, starts_at, ends_at) where active;

drop trigger if exists product_images_set_updated_at on public.product_images;
create trigger product_images_set_updated_at before update on public.product_images
for each row execute function public.set_updated_at();

create or replace function public.record_stock_movement()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.stock is distinct from old.stock then
    insert into public.stock_movements (product_id, previous_stock, new_stock, delta, reason, changed_by)
    values (new.id, old.stock, new.stock, new.stock - old.stock, 'Ajuste administrativo', (select auth.uid()));
  end if;
  return new;
end;
$$;

drop trigger if exists products_record_stock_movement on public.products;
create trigger products_record_stock_movement after update of stock on public.products
for each row execute function public.record_stock_movement();

alter table public.product_images enable row level security;
alter table public.stock_movements enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select to anon, authenticated
using (active = true and publication_status = 'published');

drop policy if exists "Public can read product images" on public.product_images;
create policy "Public can read product images" on public.product_images for select to anon, authenticated
using (exists (select 1 from public.products where products.id = product_images.product_id and products.active = true and products.publication_status = 'published'));

drop policy if exists "Admins manage product images" on public.product_images;
create policy "Admins manage product images" on public.product_images for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "Admins read stock movements" on public.stock_movements;
create policy "Admins read stock movements" on public.stock_movements for select to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins create stock movements" on public.stock_movements;
create policy "Admins create stock movements" on public.stock_movements for insert to authenticated
with check ((select public.is_admin()) and changed_by = (select auth.uid()));

grant select on public.product_images to anon, authenticated;
grant insert, update, delete on public.product_images to authenticated;
grant select, insert on public.stock_movements to authenticated;
grant usage, select on sequence public.product_images_id_seq, public.stock_movements_id_seq to authenticated;

create or replace function public.admin_store_quality()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  issues jsonb := '[]'::jsonb;
  issue_count bigint := 0;
  total_checks bigint := 0;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  select coalesce(jsonb_agg(issue order by severity_order, label), '[]'::jsonb), count(*)
  into issues, issue_count
  from (
    select jsonb_build_object('type','missing_image','severity','critical','view','products','entity','product','id',p.id,'label',p.name,'detail','Produto sem foto principal') issue, 1 severity_order, p.name label
    from public.products p where p.active and nullif(trim(p.image_url),'') is null
    union all
    select jsonb_build_object('type','out_of_stock','severity','critical','view','stock','entity','product','id',p.id,'label',p.name,'detail','Produto ativo sem estoque'), 1, p.name
    from public.products p where p.active and p.stock = 0
    union all
    select jsonb_build_object('type','missing_category','severity','critical','view','products','entity','product','id',p.id,'label',p.name,'detail','Categoria ausente ou inválida'), 1, p.name
    from public.products p left join public.categories c on c.name = p.category
    where p.active and (nullif(trim(p.category),'') is null or c.id is null)
    union all
    select jsonb_build_object('type','invalid_price','severity','critical','view','products','entity','product','id',p.id,'label',p.name,'detail','Preço precisa ser maior que zero'), 1, p.name
    from public.products p where p.active and p.price <= 0
    union all
    select jsonb_build_object('type','incomplete_product','severity','warning','view','products','entity','product','id',p.id,'label',p.name,'detail','Descrição ou categoria incompleta'), 2, p.name
    from public.products p where p.active and (nullif(trim(p.description),'') is null or nullif(trim(p.category),'') is null)
    union all
    select jsonb_build_object('type','inactive_category','severity','warning','view','categories','entity','category','id',c.id,'label',c.name,'detail','Categoria inativa possui produtos ativos'), 2, c.name
    from public.categories c where not c.active and exists (select 1 from public.products p where p.active and p.category = c.name)
    union all
    select jsonb_build_object('type','expired_offer','severity','warning','view','offers','entity','product','id',p.id,'label',p.name,'detail','Oferta vencida ainda possui desconto'), 2, p.name
    from public.products p where p.discount > 0 and p.promotion_ends_at is not null and p.promotion_ends_at < now()
    union all
    select jsonb_build_object('type','incomplete_service','severity','warning','view','services','entity','service','id',s.id,'label',s.name,'detail','Serviço ativo com dados obrigatórios incompletos'), 2, s.name
    from public.services s where s.active and (nullif(trim(s.description),'') is null or (s.price_type <> 'consult' and greatest(s.price,s.promotional_price,s.starting_price) <= 0))
    union all
    select jsonb_build_object('type','broken_banner','severity','warning','view','banners','entity','banner','id',b.id,'label',b.title,'detail','Banner ativo sem imagem'), 2, b.title
    from public.banners b where b.active and nullif(trim(b.image_url),'') is null
  ) quality;

  select greatest(1,
    (select count(*) * 5 from public.products) +
    (select count(*) * 2 from public.categories) +
    (select count(*) * 3 from public.services) +
    (select count(*) * 2 from public.banners)
  ) into total_checks;

  return jsonb_build_object(
    'score', greatest(0, round((1 - least(issue_count::numeric / total_checks, 1)) * 100)),
    'issues_total', issue_count,
    'issues', issues,
    'products_total', (select count(*) from public.products),
    'products_active', (select count(*) from public.products where active),
    'products_inactive', (select count(*) from public.products where not active),
    'products_out_of_stock', (select count(*) from public.products where active and stock = 0),
    'products_low_stock', (select count(*) from public.products where active and stock > 0 and stock <= stock_min),
    'products_without_image', (select count(*) from public.products where active and nullif(trim(image_url),'') is null),
    'products_without_category', (select count(*) from public.products where active and nullif(trim(category),'') is null),
    'stock_units', (select coalesce(sum(stock),0) from public.products),
    'categories_total', (select count(*) from public.categories),
    'offers_active', (select count(*) from public.products where active and discount > 0 and (promotion_starts_at is null or promotion_starts_at <= now()) and (promotion_ends_at is null or promotion_ends_at >= now())),
    'services_active', (select count(*) from public.services where active),
    'banners_active', (select count(*) from public.banners where active and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at >= now())),
    'updated_at', now()
  );
end;
$$;

revoke all on function public.admin_store_quality() from public, anon;
grant execute on function public.admin_store_quality() to authenticated;

create or replace function public.admin_global_search(search_term text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  needle text := trim(coalesce(search_term,''));
  results jsonb;
begin
  if not public.is_admin() then
    raise exception 'not_authorized' using errcode = '42501';
  end if;
  if length(needle) < 2 then return '[]'::jsonb; end if;

  select coalesce(jsonb_agg(item order by rank, label), '[]'::jsonb)
  into results
  from (
    select * from (
      select jsonb_build_object('type','product','view','products','id',p.id,'label',p.name,'detail',concat_ws(' • ',p.category,p.platform,'Estoque '||p.stock)) item, 1 rank, p.name label
      from public.products p
      where concat_ws(' ',p.name,p.category,p.subcategory,p.brand,p.platform,p.sku,p.search_terms) ilike '%'||needle||'%'
      union all
      select jsonb_build_object('type','order','view','orders','id',o.id,'label','#'||coalesce(to_jsonb(o)->>'order_number',o.id::text),'detail',concat_ws(' • ',o.customer_name,o.customer_phone,o.status)), 2, coalesce(o.customer_name,'')
      from public.orders o
      where concat_ws(' ',o.id::text,to_jsonb(o)->>'order_number',o.customer_name,o.customer_email,o.customer_phone,o.status) ilike '%'||needle||'%'
      union all
      select jsonb_build_object('type','service','view','services','id',s.id,'label',s.name,'detail',concat_ws(' • ',s.model,s.description)), 3, s.name
      from public.services s where concat_ws(' ',s.name,s.model,s.description) ilike '%'||needle||'%'
      union all
      select jsonb_build_object('type','category','view','categories','id',c.id,'label',c.name,'detail','Categoria do catálogo'), 4, c.name
      from public.categories c where c.name ilike '%'||needle||'%'
    ) all_results
    order by rank, label
    limit 30
  ) limited_results;
  return results;
end;
$$;

revoke all on function public.admin_global_search(text) from public, anon;
grant execute on function public.admin_global_search(text) to authenticated;

commit;
